baseURL = 'https://soya2.github.io/'
languageCode = 'en-us'
title = "Soya's blog"
theme = 'nostyleplease'

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.zh]
    languageName = "中文"
    weight = 2
